inherited FrmCadastroUF: TFrmCadastroUF
  ActiveControl = EdtCodigo
  Caption = 'Cadastro de UF'
  ClientHeight = 237
  ClientWidth = 466
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  ExplicitWidth = 472
  ExplicitHeight = 261
  PixelsPerInch = 96
  TextHeight = 13
  inherited W7Panel2: TW7Panel
    Top = 188
    Width = 466
    ExplicitTop = 188
    ExplicitWidth = 466
    inherited BtnFechar: TAeroBitBtn
      Left = 363
      ExplicitLeft = 363
    end
    inherited BtnSalvar: TAeroBitBtn
      Left = 157
      ExplicitLeft = 157
    end
    inherited BtnExcluir: TAeroBitBtn
      Left = 260
      ExplicitLeft = 260
    end
  end
  object EdtCodigo: TAdvEditBtn
    Left = 32
    Top = 56
    Width = 80
    Height = 21
    Flat = False
    LabelCaption = 'C'#243'digo'
    LabelPosition = lpTopLeft
    LabelFont.Charset = DEFAULT_CHARSET
    LabelFont.Color = clWindowText
    LabelFont.Height = -11
    LabelFont.Name = 'Tahoma'
    LabelFont.Style = []
    Lookup.Separator = ';'
    Color = clWindow
    ReadOnly = False
    TabOrder = 1
    Visible = True
    Version = '1.3.3.1'
    ButtonStyle = bsButton
    ButtonWidth = 18
    Etched = False
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000FFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFA5A5A57F7F7FC2C2C2D8D8D8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA6A6A6E6D7D78D8D8DFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFAFAFAFCDC4C4979797FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB6B6B6B3B1B190
      9090848484848484B4B4B4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFAFAFAFBAB7B3F6F1EDF7F2EEBBB8B6C4C4C4FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAED
      E0D2F5EDE7F5EDE7F0E5DAAAAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFB1B1B1ECDECFECDBCAECDBCAEEE2D4B1B1B1FFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD4D4D4C9
      C4C0F4EEE8F4EEE8C9C5C0D4D4D4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD7D7D7BDBDBDBDBDBDD7D7D7FFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
    OnClickBtn = EdtCodigoClickBtn
  end
  object EdtDescricaoCompleta: TAdvEdit
    Left = 32
    Top = 106
    Width = 257
    Height = 21
    LabelCaption = 'Descri'#231#227'o reduzida'
    LabelPosition = lpTopLeft
    LabelFont.Charset = DEFAULT_CHARSET
    LabelFont.Color = clWindowText
    LabelFont.Height = -11
    LabelFont.Name = 'Tahoma'
    LabelFont.Style = []
    Lookup.Separator = ';'
    Color = clWindow
    MaxLength = 30
    TabOrder = 2
    Visible = True
    Version = '2.9.1.1'
  end
  object EdtDescricao: TAdvEdit
    Left = 152
    Top = 56
    Width = 65
    Height = 21
    LabelCaption = 'Descri'#231#227'o'
    LabelPosition = lpTopLeft
    LabelFont.Charset = DEFAULT_CHARSET
    LabelFont.Color = clWindowText
    LabelFont.Height = -11
    LabelFont.Name = 'Tahoma'
    LabelFont.Style = []
    Lookup.Separator = ';'
    Color = clWindow
    MaxLength = 2
    TabOrder = 3
    Visible = True
    Version = '2.9.1.1'
  end
end
